from . import school_student
from . import school_teacher
from . import school_assignment
from . import school_leave
from . import student_submit
from . import school_timetable
from . import student_result
from . import school_academic
from . import school_exam
from . import school_admission
from . import student_Attendance
from . import school_subject
from . import school_course
from . import school_fees
from . import school_about
from . import school_award
from . import school_bookissue
from . import homepage
from . import fees_status
from . import inherit_sale_order
from . import inherit_invoice
from . import inherit_sale_order_line
from . import inherit_stock_move
from . import inherit_stock_picking
from . import inherit_project_task
from . import inherit_purchase
from . import inherit_stock_rule
from . import mrp_production
from . import inherit_product_template
from . import stock_picking_type
from . import product_product
